### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by kirti-tyagi** [ahkohd/naijahacks-fort-mobile#1]
I tried running your code on android studio but it shows me server connecting issues. Can you please help me with it? 
I'm working on windows 10

**Comment by ahkohd** [comment]
The project's sever is currently offline.

**Comment by kirti-tyagi** [comment]
How can I make one for myself? I need it for my project.

**Comment by ahkohd** [comment]
https://towardsdatascience.com/plant-ai-deploying-deep-learning-models-9dda5f6c1088
https://github.com/Emmarex/naijahacks-fort-API
A detailed post from a team mate.

**Comment by kirti-tyagi** [comment]
I got Mobile App code from here itself and I tried running but started
facing issues. My model perfectly works till the last step i.e Django.

**Comment by ahkohd** [comment]
Am not  django developer, maybe you should raise an issue in his repo.
